name = "BayesScoreCalExamples"
uuid = "6e0c5a35-739d-4bd5-a77e-7f2f987dd6fd"
authors = ["Joshua J Bon"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
